### ISSUE TITLE
java.lang.RuntimeException

### ISSUE THREAD

**Issue by NotWhiteRice** [DJtheRedstoner/DevAuth#13]
When i try running DevAuth i get: Caused by: java.lang.RuntimeException: Received bad status 400 Bad Request body: {"error":"invalid_request","error_description":"Tokens issued for the 'Single-Page Application' client-type should only be redeemed via cross-origin requests. If your client does not send the Origin header, you should register it as a 'Native' client-type instead.","correlation_id":"c523c866-18f5-4fbb-9aff-e96f6a974c7a"}

I've used both the .jar and the maven dependency, and they both have the same problem

**Comment by DJtheRedstoner** [comment]
You will need to launch the game twice after installing the 1.2.0 update. If this issue persists, delete the `microsoft_accounts.json` file in the devauth config folder.

**Comment by IMB11** [comment]
This doesn't seem to fix the issue - I believe the OAuth system might have changed slightly somewhere? Other in-dev auth mods aren't working either.

**Comment by IMB11** [comment]
Nevermind, I had to delete the entire `~/.config/devauth` folder.

**Comment by DJtheRedstoner** [comment]
Resolved.
