### ISSUE TITLE
Feature Request: Support environment variables

### ISSUE THREAD

**Issue by Hacksore** [DJtheRedstoner/DevAuth#2]
Very cool mod and I appreciate you writing it! 

I have been using [in-game-account-switcher](https://www.curseforge.com/minecraft/mc-mods/in-game-account-switcher) however it's rather clunky to have to select your account every launch. Would it be acceptable to add some environment variables in which the mod could look for?

Perhaps something like `MINECRAFT_USERNAME` and `MINECRAFT_PASSWORD`?

**Comment by DJtheRedstoner** [comment]
What advantages would he environment variables provide over the current config system?

**Comment by Hacksore** [comment]
I don't really think it does add much value in hindsight. If I want this feature I can just add it to my mod via `System.setProperty` when in dev mode.
