### ISSUE TITLE
Encryption 

### ISSUE THREAD

**Issue by JaaiDead** [DJtheRedstoner/DevAuth#5]
Add a Encryption PR.

**Comment by DJtheRedstoner** [comment]
Please be more specific. If you want the Microsoft account store encrypted please say so. Assuming that is what you want, how do you propose encrypting it? Storing a key in a separate file (offers limited protection beyond security through obscurity). Or maybe prompting the user for a decryption key/password every time? Any kind of encryption would be a compromise between security and ease of use. Additionally, why do you think encryption is necessary? If an application reads this file with malicious intent, there is already a problem and encrypting the file just prevents one specific attack against DevAuth.

**Comment by JaaiDead** [comment]
Since there will no malicious intent. There might be a problem in ease of use.  I just thought that it might be a problem. Now its clear.
