### ISSUE TITLE
Config issue

### ISSUE THREAD

**Issue by Sunderw3k** [DJtheRedstoner/DevAuth#7]
The default config in .devauth/config.toml has a missing `c` in `defaultAccount`. This is very annoying considering its a small typo. Please fix

**Comment by DJtheRedstoner** [comment]
This was already fixed in a0691f26016d2bcb0feb67fe7f90ab41c223aefa and that commit was included in the 1.0.0 release. Make sure you are up to date and delete you config to regenerate it with the default.
